### ISSUE TITLE
Workflow Run Failure: Header Issues 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#1]
## Describe the issue
BAM headers special characters and does not match the read group ID in SONG analysis cause the runs to fail, eg, read group ID in SONG `CRUK-CI:LP6007566-DNA_A01_1` vs `CRUK-CI:LP6007566-DNA_A01'` in the BAM.

## List all runids affected
- wes-f2ce9b0183544296aac7a2a196e63597
- wes-1b0be978676d4fc8801906eeab5fc632
- wes-f2ce9b0183544296aac7a2a196e63597
- wes-1b0be978676d4fc8801906eeab5fc632
- wes-14bebffab5334b28882a0752bfc3adf6
- wes-d33c60c0435c44a8b96e70d2700c5771
- wes-e508230cc7f04b4391ecba5d93a98e8f
- wes-e870820370af4b398f4e757960527a4e
- wes-f9c5039c8dc14ab39c1fd0e1b361b4d2

## Approach to address this
In SONG payload add a new field in `read_groups` section: `read_group_id_in_bam`. The value matches exactly the RG ID in the BAM header. This will allow us to associate read group id in BAM to read group ID in the SONG payload unambiguously. We then can use `submitter_read_group_id` (instead of `read_group_id_in_bam`) in the aligned BAM at the bwa-mem alignment step.
```
{ 
  "submitter_read_group_id": "CRUK-CI:LP6007421-DNA_A01_1",
  "read_group_id_in_bam": "CRUK-CI:LP6007421-DNA_A01'"
}
```

## Tasks need to be completed (mostly sequentially):
- [x] update `seq-data-to-lane-bam` module
- [x] update `bwa-mem-aligner` module
- [x] update `payload-gen-dna-seq-qc` module
- [x] update metadata schemas for `sequencing_alignment` and `sequencing_experiment`
- [x] update metadata schemas on QA SONG server
- [x] test updated pipeline locally
- [x] test updated pipeline on a VM
- [x] use tiny BAM to test updated pipeline on QA K8S cluster
- [x] release `0.1.1` for metadata updated schemas in github [repo](https://github.com/icgc-argo/argo-metadata-schemas)
- [x] update metadata schemas on `intermediate-song` server
- [x] update SONG payloads with the new field where RG ID overwriting is needed
- [x] release new pipeline version `1.0.2`
- [x] update metadata schemas on PROD SONG server
- [x] relaunch runs previously failed on PROD K8S cluster

## Exit criteria
- [x] Issue has been resolved
- [x] Run is resumed

**Comment by junjun-zhang** [comment]
Now able to successfully run jobs with mismatch read group ID in metadata and BAM header, for example this run: `wes-ad185afb82644ecf9a9dffefdfcb76a7`.
