### ISSUE TITLE
Write Generalized Workflow for Data Transfer to ARGO

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#246]
Write a generalized workflow for data transfer to ARGO, would be used by several/multiple programs

Linda to provide support to help Edmund setup workflows, etc

**Comment by lindaxiang** [comment]
- [x] Set up workflow github repo: https://github.com/icgc-argo/argo-data-submission
- [ ] GitHub README page including
- Workflow diagram
- Detail workflow steps
- [x] Use wfpm to dev
wfpm Ref:
- Github: https://github.com/icgc-argo/wfpm. 
- Docs: https://wfpm.readthedocs.io/en/latest/

**Comment by b-f-chan** [comment]
Suggestion - Write SOP first before setup

**Comment by b-f-chan** [comment]
Do we want a full fleshed out workflow here?  Some manual intervention steps needed, not sure if fully scripted workflow can be done.

However, draft has been sent to Linda & Hardeep for review, @edsu7 needs to move to public/team-accessible repo from his personal one.

Concern is having additional layer of wrapper on top of wrapper, but suggestion is set as separate tools and in the workflow provide a parameter to indicate which tool they want to use, then you don't have to do nested wrappers

@lindaxiang to start a template that @edsu7 can use

**Comment by b-f-chan** [comment]
@edsu7 - Suggestion is to create tickets for each module of the workflow so it's easier to track 

@b-f-chan - Convert to epic so we can track the sub-tasks

**Comment by b-f-chan** [comment]
@lindaxiang @edsu7 @hknahal - If we can create a small wiki page on the ARGO wikispace describing this proposal along with the flow diagram, then @mcourtot can review before our review meeting

**Comment by b-f-chan** [comment]
Wiki:
https://wiki.oicr.on.ca/display/icgcargotech/ICGC-ARGO+Molecular+Data+Submission

**Comment by b-f-chan** [comment]
#260 is final ticket before this epic can be closed

**Comment by b-f-chan** [comment]
#260 is completed.  Documentation will be done separately outside of this epic in #281, we can now close this epic.
