### ISSUE TITLE
Adjustments to RNA-Seq Aln WF

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#287]
The RNA-Seq Aln WF is expected to have some adjustments
- [ ] wait for the addition of transcriptome output from STAR and test
    - [ ] Andre (RNA-Seq wg) will make changes to STAR tool (https://github.com/icgc-argo-workflows/rna-seq-alignment/issues/30)
    - [ ] payload-gen tool adjustment for STAR outputs to include transcriptome BAM. (https://github.com/icgc-argo-workflows/data-processing-utility-tools/issues/162)
    - [ ] whole workflow adjustment to incorporate the updates of the above two tools. (https://github.com/icgc-argo-workflows/rna-seq-alignment/issues/31)

- [ ] https://github.com/icgc-argo-workflows/rna-seq-alignment/issues/29

Blocking:
- put the processing of RNA-Seq aln data on hold in Production (ref: https://github.com/icgc-argo/workflow-roadmap/issues/271)

**Comment by b-f-chan** [comment]
@lindaxiang might contact Andre to check status and try and push things forward

**Comment by b-f-chan** [comment]
@lindaxiang needs to address this week

**Comment by b-f-chan** [comment]
Ticket has been addressed and workflow released, we are good to go for APGI.  Closing.
