### ISSUE TITLE
Workflow Authorization Updates

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#33]
- [x] Deploy workflow-management k8s secret management with api-key run profile
- [x] Nextflow Update to DSL2 and  publish a new release: https://github.com/icgc-argo/nextflow-data-processing-utility-tools
- [x] Nextflow Update inside of Workflow Management
- [x] Test download from icgc score and upload to rdpc qa score in one workflow  (verify secret management with different api tokens) https://github.com/icgc-argo/roadmap/issues/554
- [x] Edit model T to not pass API keys https://github.com/icgc-argo/roadmap/issues/554
- [x] Integrate the new song/score modules into all workflows and publish the new versions.https://github.com/icgc-argo/workflow-roadmap/issues/36 `WIP`
- [x] full dev/qa cycle/test and ready to go to prod (official wf with new modules) https://github.com/icgc-argo/workflow-roadmap/issues/36 `WIP`
- [x] Address Score upload issues  https://github.com/overture-stack/score/issues/276
- [x] address failed workflows by resuming [Workflow Run Failure: Score upload] https://github.com/icgc-argo/workflow-roadmap/issues/37 
- [x] Deploy QA Environment to prod  https://github.com/icgc-argo/roadmap/issues/553
- [x] Check the Elastic format in prod; make sure its indexed against the latest mapping
- [x] fix k8 secret bug https://github.com/icgc-argo/nextflow-data-processing-utility-tools/issues/23 `WIP`
- [x] Cancel the stuck jobs  https://github.com/icgc-argo/roadmap/issues/553 
- [x] Import next Data batch to intermediate song https://github.com/icgc-argo/roadmap/issues/565
-------> can turn on WFs with new versions 
- [x] Update scope resolution in Ego https://github.com/overture-stack/ego/issues/493
- [x] Update Ego Version 
- [x] Update Song-to-Score authorization communication https://github.com/overture-stack/roadmap/issues/90
- [x] Update workflow-management to use oauth2 profile 
- [x] Turn on secure profile in [song search, wf search,  wf-management]
- [x] Tag Song with JWT changes and deploy (https://github.com/overture-stack/SONG/issues/702)
- [x] Test in qa environment 

-------> No API Keys needed monthly for song/score/management

- [x] Add Auth to Workflow ui   (https://github.com/icgc-argo/workflow-ui/issues/78)
- [x] Add Auth to Model T (https://github.com/icgc-argo/workflow-roadmap/issues/75)
- [x] Test nginx reverse proxy to ensure headers are being passed
