### ISSUE TITLE
ARGO data migration from Collab to Azure

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#381]
With Collaboratory shutting down at the end of 2023, we need to migrate all ARGO data from Collab to Azure. 
- This [google doc](https://docs.google.com/document/d/17JkFZOuphgeozTkhLoBqlMhFOtQl5_xV5MOlWLPalEQ/edit?usp=sharing) contains the draft plan for the data migration.
- The [ticket](https://github.com/icgc-argo/workflow-roadmap/issues/349) will generate the auditing report for ARGO data census in Collab. 

Migration is expected to be completed at the end of Oct. 

We want to do initial tests in order to make sure the proposed data migration strategy works as expected:

- [ ] Create song/score instances running in Azure which is hooked into an Azure bucket
- [ ] Copy test data objects utilizing Rclone from Collab to Azure 
- [ ] Test song/score upload/download works as expected

**Comment by lindaxiang** [comment]
Thanks to Jared, this has been addressed.
