### ISSUE TITLE
Ceph Storage Middleware POC

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#86]
WF --> NFS --> Ceph Storage 

The problem is the Ceph Storage
- limit the number of jobs you schedule to each NFS 
- This is a collab specific issue.  
- Choose which volume a job goes into (in addition to the number of jobs) to distribute the load across Ceph storage 
- Model-T computes the NFS to use in real-time.  It looks at all exisiting running wfs, gets the directory in use, counts the wf running on each directory and makes sure that any single directory is not exceeding the limit it its allowed number of jobs. 

- without empty-dir 20 jobs in parallel 24+ will fail 
- with empty-dir 
- middleware to append the workflow run request with the correct NFS directory to the run request. 

The current setup of the WF execution system will also need to be updated for this feature: https://wiki.oicr.on.ca/display/icgcargotech/WES+setup+-+revisited

## After Investigation 

- [x] We have to refactor WF-management to send run requests to rabbitmq and consume them from rabbit. 
- [x] Setup a state verifier in between the rabbitmq producer and consumer to verify Runs state transitions
- [x] Relay needs to accept WF management events  
- [x] verify post-run-start error monitor is working
- [x] we need to create a plugin service which will schedule Runs by taking QUEUED runs and moving them to INITIALIZING
- [x] Move wf-mgmt controller into wf-search and rebrand wf-search as wf-api
